# A simple action usage
name: Build Kernel for Zenfone 5Z
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Build Kernel
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/holzip/android_kernel_asus_sdm845
          kernel-dir: msm-4.9
          kernel-branch: lineage-22.2
          config: vendor/asus/Z01R.config
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          vendor: true
          vendor-dir: vendor
          vendor-url: https://github.com/TheMuppets/proprietary_vendor_asus_Z01R
          android-version: 12
          aosp-clang-version: r383902
